version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
dockers:
  - image_templates:
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-arm64v8"
  - name_template: "ghcr.io/reddec/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-arm64v8"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

