// Code generated by gen. DO NOT EDIT.
package home

import (
	"embed"
	"sync"

	"github.com/reddec/dreaming-bard/internal/server/views"
)

//go:embed all:views
var assets embed.FS

var viewIndex = sync.OnceValue(func() *views.DynamicView[indexParams] {
	return views.InheritBase[indexParams](assets, "views/index.gohtml")
})

