// Code generated by gen. DO NOT EDIT.
package blueprint

import (
	"embed"
	"sync"

	"github.com/reddec/dreaming-bard/internal/server/views"
)

//go:embed all:views
var assets embed.FS

var viewList = sync.OnceValue(func() *views.DynamicView[listParams] {
	return views.InheritBase[listParams](assets, "views/list.gohtml")
})

var viewIndex = sync.OnceValue(func() *views.DynamicView[indexParams] {
	return views.InheritBase[indexParams](assets, "views/index.gohtml")
})

var viewWizard = sync.OnceValue(func() *views.DynamicView[wizardParams] {
	return views.InheritBase[wizardParams](assets, "views/wizard.gohtml")
})

