// Code generated by gen. DO NOT EDIT.
package roles

import (
	"embed"
	"sync"

	"github.com/reddec/dreaming-bard/internal/server/views"
)

//go:embed all:views
var assets embed.FS

var viewEdit = sync.OnceValue(func() *views.DynamicView[editParams] {
	return views.InheritBase[editParams](assets, "views/edit.gohtml")
})

var viewNew = sync.OnceValue(func() *views.DynamicView[newParams] {
	return views.InheritBase[newParams](assets, "views/new.gohtml")
})

var viewList = sync.OnceValue(func() *views.DynamicView[listParams] {
	return views.InheritBase[listParams](assets, "views/list.gohtml")
})

var viewIndex = sync.OnceValue(func() *views.DynamicView[indexParams] {
	return views.InheritBase[indexParams](assets, "views/index.gohtml")
})

var viewImport = sync.OnceValue(func() *views.DynamicView[importParams] {
	return views.InheritBase[importParams](assets, "views/import.gohtml")
})

